// Mapper for various categories
const mapper = {
  // General Categories
  intervention: 'Intervention',
  outcome: 'Outcome',
  popu: 'Population',
  topic: 'Topic',
  reviews: 'Reviews',
  studies: 'Studies',
  particip: 'Participants',
  lit_search_dates: 'Literature Search Dates',
  CustomGroup: 'Custom Group',
  rev: 'Review Type',

  // Demographics
  age__group: 'Age Group',
  vaccine__options: 'Age Group',
  ado_10__17: 'Adolescents (10-18 years)',
  adu_18__64: 'Adults (18+)',
  chi_2__9: 'Children (2-9 years)',
  eld_65__10000: 'Elderly (65+)',
  nb_0__1: 'Newborn (0-1 years)',
  immune__status: 'Immune Status',
  specific__group: 'Specific Group',
  hty: 'Healthy',
  hcw: 'Healthcare Workers (hcw)',
  pcg: 'Parents/Caregivers (cg)',
  pw: 'Pregnant Women (pw)',
  tra: 'Travellers (tra)',

  // Diseases and Vaccines
  live: 'Live',
  vpd: 'Age Group',
  covid: 'Covid-19',
  deng: 'Dengue (deng)',
  diph: 'Diphtheria (diph)',
  hib: 'Haemophilus influenzae type b',
  ha: 'Hepatitis A (ha)',
  hb: 'Hepatitis B (hb)',
  hc: 'Hepatitis C (hc)',
  he: 'Hepatitis E (he)',
  hs: 'Herpes simplex (hs)',
  hz: 'Shingles, Herpes zoster (hz)',
  hiv: 'HIV/AIDS (hiv)',
  hpv: 'Human papillomavirus (HPV)',
  infl: 'Influenza (infl)',
  je: 'Japanese encephalitis (je)',
  leis: 'Leishmaniasis (leis)',
  lyme: 'Borreliosis (Lyme)',
  mala: 'Malaria (mala)',
  meas: 'Measles (meas)',
  meni: 'Meningococcal (meni)',
  mump: 'Mumps',
  myle: 'Leprosy (myle)',
  myva: 'Mycobacterium vaccae (myva)',
  pert: 'Pertussis (pert)',
  plag: 'Plague (plag)',
  pneu: 'Pneumococcal (pneu)',
  poli: 'Poliomyelitis (poli)',
  pseu: 'Pseudomonas aeruginosa (psue)',
  rabi: 'Rabies (rabi)',
  rota: 'Rotavirus (rota)',
  rsv: 'Respiratory syncytial virus (RSV)',
  rube: 'Rubella (rube)',
  salm: 'Salmonella (salm)',
  shig: 'Shigella (shig)',
  smal: 'Smallpox (smal)',
  strb: 'Streptococcus group B (strb)',
  tt: 'Tetanus (tt)',
  tbe: 'Tick-borne encephalitis (tbe)',
  tetanus: 'Tetanus',
  tb: 'Tuberculosis (tb)',
  typh: 'Typhoid (typh)',
  vari: 'Varicella (Chickenpox)',
  yf: 'Yellow fever (yf)',
  zika: 'Zika',
  anth: 'Anthrax (anth)',
  camp: 'Campylobacter (camp)',
  chol: 'Cholera (chol)',
  coxi: 'Q fever (coxi)',
  ebol: 'Ebola (ebol)',
  ente: 'Enterovirus (ente)',
  esch: 'Escherichia coli (ETEC)',

  // Risk Factors and Outcomes
  rf: 'Risk Factor (rf)',
  va: 'Vaccine/Vaccination (va)',
  kaa: 'Acceptance (kaa)',
  dea: 'Death (dea)',
  hos: 'Hospitalization (hos)',
  icu: 'ICU',
  inf: 'Infection (inf)',
  eff: 'Efficacy/Effectiveness (eff)',
  adm: 'Administration (adm)',
  cov: 'Coverage (cov)',
  eco: 'Economic Aspects (eco)',
  eth: 'Ethical Issues (eth)',
  log: 'Logistics (log)',
  mod: 'Modeling (mod)',
  saf: 'Safety (saf)'
};

export { mapper };
