// Mapper for various categories
const mapper = {
  Year: "Pulication Year",
  vaccine__options: 'Vaccine Options',
  vpd: 'Vaccine Preventable Diseases',
  aden: 'Adenovirus',
  intervention: 'Intervention',
  outcome: 'Outcome',
  popu: 'Population',
  topic: 'Topic',
  reviews: 'Reviews',
  studies: 'Studies',
  particip: 'Participants',
  lit_search_dates: 'Literature Search Dates',
  CustomGroup: 'Custom Group',
  rev: 'Review Type',
  age__group: 'Age Group',
  live: 'Live',
  covid: 'Covid-19',
  deng: 'Dengue',
  diph: 'Diphtheria',
  hib: 'Haemophilus influenzae type b',
  ha: 'Hepatitis A',
  hb: 'Hepatitis B',
  hc: 'Hepatitis C',
  he: 'Hepatitis E',
  hs: 'Herpes simplex',
  hz: 'Shingles, Herpes zoster',
  hiv: 'HIV/AIDS',
  hpv: 'Human papillomavirus',
  infl: 'Influenza',
  je: 'Japanese encephalitis',
  leis: 'Leishmaniasis',
  lyme: 'Borreliosis',
  mala: 'Malaria',
  meas: 'Measles',
  meni: 'Meningococcal',
  mump: 'Mumps',
  myle: 'Leprosy',
  myva: 'Mycobacterium vaccae',
  pert: 'Pertussis',
  plag: 'Plague',
  pneu: 'Pneumococcal',
  poli: 'Poliomyelitis',
  pseu: 'Pseudomonas aeruginosa',
  rabi: 'Rabies',
  rota: 'Rotavirus',
  rsv: 'Respiratory syncytial virus',
  rube: 'Rubella',
  salm: 'Salmonella',
  shig: 'Shigella',
  smal: 'Smallpox',
  strb: 'Streptococcus group B',
  tt: 'Tetanus (tt)',
  tbe: 'Tick-borne encephalitis',
  tetanus: 'Tetanus',
  tb: 'Tuberculosis',
  typh: 'Typhoid',
  vari: 'Varicella (Chickenpox)',
  yf: 'Yellow fever',
  zika: 'Zika',
  anth: 'Anthrax',
  camp: 'Campylobacter',
  chol: 'Cholera',
  coxi: 'Q fever',
  ebol: 'Ebola',
  ente: 'Enterovirus',
  esch: 'Escherichia coli',
  ado_10__17: 'Adolescents (10-18 years)',
  adu_18__64: 'Adults (18+)',
  chi_2__9: 'Children (2-9 years)',
  eld_65__10000: 'Elderly (65+)',
  nb_0__1: 'Newborn (< 1 years)',
  immune__status: 'Immune Status',
  specific__group: 'Specific Group',
  hty: 'Healthy',
  hcw: 'Healthcare Workers',
  pcg: 'Parents/Caregivers',
  pw: 'Pregnant Women',
  tra: 'Travellers',
  rf: 'Risk Factor',
  va: 'Vaccine/Vaccination',
  kaa: 'Acceptance',
  dea: 'Death',
  hos: 'Hospitalization',
  icu: 'ICU',
  inf: 'Infection',
  eff: 'Efficacy/Effectiveness',
  adm: 'Administration',
  cov: 'Coverage',
  eco: 'Economic Aspects',
  eth: 'Ethical Issues',
  log: 'Logistics',
  mod: 'Modeling',
  saf: 'Safety',
  non__djuvanted: 'Non Adjuvanted',
  adjuvants: 'Adjuvants',
  quad: 'Quadrivalent',
  biva: 'Bivalent',
  en: 'English',
  imu: 'Immunization'
};

export { mapper };
